# ============================================================
# ENCRYPTED CREDENTIALS
# ============================================================
# These are generated by the helper at the bottom of this file.
# To update: run .encrypt_credentials() with your values,
# then paste the output here.
#
# >>>>>>>>>> PLACEHOLDER: Replace these three strings <<<<<<<<<<
# with the output from .encrypt_credentials()
#
.ENCRYPTED_ACCESS_KEY_ID     <- "PASTE_ENCRYPTED_ACCESS_KEY_HERE"
.ENCRYPTED_SECRET_ACCESS_KEY <- "PASTE_ENCRYPTED_SECRET_KEY_HERE"
.ENCRYPTED_ENDPOINT_URL      <- "PASTE_ENCRYPTED_ENDPOINT_HERE"

# >>>>>>>>>> PLACEHOLDER: Replace with your chosen username <<<<<<<<<<
.VALID_USERNAME <- "REPLACE_WITH_USERNAME"


# ============================================================
# INTERNAL: Encryption helpers (XOR cipher with base64)
# ============================================================
.xor_cipher <- function(input_bytes, key_string) {
  key_bytes <- charToRaw(key_string)
  key_len <- length(key_bytes)
  out <- raw(length(input_bytes))
  for (i in seq_along(input_bytes)) {
    out[i] <- xor(input_bytes[i], key_bytes[((i - 1) %% key_len) + 1])
  }
  out
}

.encrypt_string <- function(plain_text, password) {
  raw_input <- charToRaw(plain_text)
  encrypted <- .xor_cipher(raw_input, password)
  base64enc::base64encode(encrypted)
}

.decrypt_string <- function(encoded_text, password) {
  encrypted <- base64enc::base64decode(encoded_text)
  decrypted <- .xor_cipher(encrypted, password)
  rawToChar(decrypted)
}


# ============================================================
# CREDENTIAL GENERATOR (run this once locally to get your
# encrypted strings, then paste them above)
# ============================================================
# To use:
#   1. Open R
#   2. Run: source("R/r2.R")
#   3. Run the command below with YOUR actual values:
#
#   .encrypt_credentials(
#     access_key_id     = "your_actual_access_key",
#     secret_access_key = "your_actual_secret_key",
#     endpoint_url      = "https://your_actual_endpoint.r2.cloudflarestorage.com",
#     password          = "REPLACE_WITH_PASSWORD"
#   )
#
#   4. Copy the three output strings into the PLACEHOLDER
#      section at the top of this file.
#   5. Commit and push.
#
# >>>>>>>>>> PLACEHOLDER: Replace "REPLACE_WITH_PASSWORD" <<<<<<<<<<
# in the function call example above with your chosen password.
#
.encrypt_credentials <- function(access_key_id, secret_access_key,
                                  endpoint_url, password) {
  if (!requireNamespace("base64enc", quietly = TRUE)) {
    stop("Install base64enc first: install.packages('base64enc')")
  }
  cat("Copy these into the top of R/r2.R:\n\n")
  cat('.ENCRYPTED_ACCESS_KEY_ID     <- "',
      .encrypt_string(access_key_id, password), '"\n', sep = "")
  cat('.ENCRYPTED_SECRET_ACCESS_KEY <- "',
      .encrypt_string(secret_access_key, password), '"\n', sep = "")
  cat('.ENCRYPTED_ENDPOINT_URL      <- "',
      .encrypt_string(endpoint_url, password), '"\n', sep = "")
}


# ============================================================
# EXPORTED FUNCTIONS
# ============================================================

#' Connect to the Data
#'
#' Authenticates with your username and password, then connects
#' to the data source. Must be called once per session.
#'
#' @param username Your username.
#' @param password Your password.
#'
#' @return Invisible \code{TRUE} on success.
#' @export
#'
#' @examples
#' \dontrun{
#' connect(username = "myuser", password = "mypass")
#' }
connect <- function(username, password) {

  if (missing(username) || missing(password)) {
    stop("Both username and password are required.\n",
         "Usage: connect(username = \"...\", password = \"...\")",
         call. = FALSE)
  }

  if (username != .VALID_USERNAME) {
    stop("Invalid username.", call. = FALSE)
  }

  # Attempt to decrypt — if password is wrong, we'll get garbage
  # and the connection will fail
  tryCatch({
    access_key <- .decrypt_string(.ENCRYPTED_ACCESS_KEY_ID, password)
    secret_key <- .decrypt_string(.ENCRYPTED_SECRET_ACCESS_KEY, password)
    endpoint   <- .decrypt_string(.ENCRYPTED_ENDPOINT_URL, password)
  }, error = function(e) {
    stop("Invalid password.", call. = FALSE)
  })

  Sys.setenv(
    AWS_ACCESS_KEY_ID     = access_key,
    AWS_SECRET_ACCESS_KEY = secret_key,
    AWS_DEFAULT_REGION    = "us-east-1"
  )

  ep_clean <- sub("^https?://", "", endpoint)
  ep_clean <- sub("/$", "", ep_clean)
  options(r2_endpoint = ep_clean, r2_bucket = "espn-data")

  tryCatch({
    aws.s3::get_bucket("espn-data", max = 1, use_https = TRUE,
                       base_url = ep_clean, region = "")
    message("Connected successfully!")
  }, error = function(e) {
    stop("Invalid credentials. Check your username and password.",
         call. = FALSE)
  })

  invisible(TRUE)
}


#' List Available Dates for a Dataset
#'
#' @param dataset One of \code{"game_info_daily"}, \code{"pbp_daily"},
#'   \code{"players_box_daily"}, or \code{"stints_daily"}.
#' @return A sorted \code{Date} vector.
#' @export
list_dates <- function(dataset = c("game_info_daily", "pbp_daily",
                                    "players_box_daily", "stints_daily")) {
  dataset  <- match.arg(dataset)
  endpoint <- getOption("r2_endpoint")
  bucket   <- getOption("r2_bucket")
  if (is.null(endpoint)) stop("Not connected. Run connect() first.", call. = FALSE)

  objects <- aws.s3::get_bucket(bucket, prefix = paste0(dataset, "/"),
                                use_https = TRUE, base_url = endpoint,
                                region = "")
  keys <- sapply(objects, \(x) x$Key)
  dates <- as.Date(gsub(paste0(dataset, "/|\\.parquet"), "", keys))
  sort(dates[!is.na(dates)])
}


#' Read Daily Parquet Data
#'
#' @param dataset One of \code{"game_info_daily"}, \code{"pbp_daily"},
#'   \code{"players_box_daily"}, or \code{"stints_daily"}.
#' @param start_date Start date (inclusive), \code{"YYYY-MM-DD"} or
#'   \code{NULL} for no lower bound.
#' @param end_date End date (inclusive), \code{"YYYY-MM-DD"} or
#'   \code{NULL} for no upper bound.
#' @return A data frame.
#' @export
read_daily <- function(dataset = c("game_info_daily", "pbp_daily",
                                    "players_box_daily", "stints_daily"),
                       start_date = NULL,
                       end_date   = NULL) {
  dataset  <- match.arg(dataset)
  endpoint <- getOption("r2_endpoint")
  bucket   <- getOption("r2_bucket")
  if (is.null(endpoint)) stop("Not connected. Run connect() first.", call. = FALSE)

  available <- list_dates(dataset)
  if (!is.null(start_date)) available <- available[available >= as.Date(start_date)]
  if (!is.null(end_date))   available <- available[available <= as.Date(end_date)]

  if (length(available) == 0) {
    message("No files found for the specified date range.")
    return(data.frame())
  }

  message(sprintf("Reading %d file(s) from %s...", length(available), dataset))

  dfs <- lapply(available, function(d) {
    key <- sprintf("%s/%s.parquet", dataset, d)
    tryCatch({
      raw <- aws.s3::get_object(key, bucket = bucket, use_https = TRUE,
                                base_url = endpoint, region = "")
      tbl <- arrow::read_parquet(rawConnection(raw), as_data_frame = FALSE)

      # Convert list columns to R lists manually, then everything else normally
      list_cols <- names(which(sapply(tbl$schema$fields, function(f) {
        grepl("list", f$type$ToString())
      })))

      df <- as.data.frame(
        tbl$SelectColumns(setdiff(names(tbl), list_cols)),
        check.names = FALSE
      )

      for (col in list_cols) {
        df[[col]] <- as.list(tbl[[col]]$as_vector())
      }

      df
    }, error = function(e) {
      warning(sprintf("Failed to read %s: %s", key, e$message))
      NULL
    })
  })

  results <- Filter(Negate(is.null), dfs)
  if (length(results) == 0) return(data.frame())
  if (length(results) == 1) return(results[[1]])
  do.call(rbind, results)
}


#' Read ESPN Rosters
#'
#' @return A data frame of player roster data.
#' @export
read_rosters <- function() {
  endpoint <- getOption("r2_endpoint")
  bucket   <- getOption("r2_bucket")
  if (is.null(endpoint)) stop("Not connected. Run connect() first.", call. = FALSE)

  raw <- aws.s3::get_object("player_data/espn_rosters_25_26.csv",
                            bucket = bucket, use_https = TRUE,
                            base_url = endpoint, region = "")
  read.csv(text = rawToChar(raw))
}


#' Read ESPN Teams
#'
#' @return A data frame of team data.
#' @export
read_teams <- function() {
  endpoint <- getOption("r2_endpoint")
  bucket   <- getOption("r2_bucket")
  if (is.null(endpoint)) stop("Not connected. Run connect() first.", call. = FALSE)

  raw <- aws.s3::get_object("team_data/espn_teams_25_26.csv",
                            bucket = bucket, use_https = TRUE,
                            base_url = endpoint, region = "")
  read.csv(text = rawToChar(raw))
}
